### ISSUE TITLE
Crash Again! - Test Environment Single Player :'(

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [elix-x/Colourful-Blocks#5]
Crash Log - Client Side ["[Universal]-ColorfullBlocks-1.1.3-1.7.10 and [Universal]-Excore-1.2.3-1.7.10"]
https://gist.github.com/DPxKnightxZero/486de0a5162b0a316195

Full Client Log - ["[Universal]-ColorfullBlocks-1.1.3-1.7.10 and [Universal]-Excore-1.2.3-1.7.10"]
https://gist.github.com/DPxKnightxZero/8c5d696e1d443eb7a644

**Comment by Elix-x** [comment]
There's something realy wrong with one your mods. Previous crash was caused because one of mods was coded wrongly too (probably same that causes this). Try removing mods one by one, because there's really one mod that is causing this. Because it's repair item stack for tool material is coded wrongly.

**Comment by P3rf3ctXZer0** [comment]
Any idea what the wrong mods asm is doing? If it helps I use BetterFPS, FPSPlus+,Fastcraft, NotEnoughID's which all mess with asms. Here is a link to the mod compatability thread for FastCraft and NotenoughID's. https://github.com/fewizz/NotEnoughIDs/issues/25

**Comment by Elix-x** [comment]
No. No one of them.
One of mod that adds tool material, defines repair item stack with null item. Which is very very very bad.
"You must either not define repair item stack, or define it with valid item, but not null." - These are basics of basics of modding.

**Comment by fewizz** [comment]
@DPxKnightxZero , problem not in NEID =P
